name: tradly_app
description: "Tradly Application"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.5.0+1

  freezed: ^2.5.2

  equatable: ^2.0.7

  flutter_bloc: ^9.1.0

  flutter_svg: ^2.0.17

  supabase_flutter: ^2.8.4

  go_router: ^14.8.1

  permission_handler: ^11.4.0

  intl: 0.19.0

  responsive_framework: ^1.5.1

  flutter_native_splash: ^2.4.4

  intl_utils: ^2.8.5

  cached_network_image: ^3.4.1

  envied: ^1.1.1

  shared_preferences: ^2.5.3

  firebase_core: ^3.13.0

  firebase_messaging: ^15.2.5

  flutter_local_notifications: ^19.1.0

  freezed_annotation: ^2.4.4

  image_picker: ^1.1.2

  device_preview: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.4.11

  flutter_launcher_icons: ^0.14.3

  flutter_gen_runner: ^5.10.0

  melos: ^6.1.0

  envied_generator: ^1.1.1



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  arb_dir: lib/core/l10n
  output_dir: lib/core/resources/l10n_generated

# Config gen assets
flutter_gen:
  output: lib/core/resources/assets_generated/ 
  # Optional
  integrations:
    flutter_svg: true  